// <auto-generated />
namespace GithubStatistics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class github1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(github1));
        
        string IMigrationMetadata.Id
        {
            get { return "201908271202331_github1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
